In [84]:
import folium
import pandas as pd
import geopandas as gpd
from folium.plugins import HeatMap
import streamlit as st

In [85]:
demographic_columns = [
    'total_population', 'age', 'under_5_years', '5_to_9_years', '10_to_14_years', '15_to_19_years',
    '20_to_24_years', '25_to_29_years', '30_to_34_years', '35_to_39_years', '40_to_44_years', 
    '45_to_49_years', '50_to_54_years', '55_to_59_years', '60_to_64_years', '65_to_69_years', 
    '70_to_74_years', '75_to_79_years', '80_to_84_years', '85_years_and_over', 'less_than_high_school_graduate',
    'high_school_graduate', 'some_college_or_associate\'s_degree', 'bachelor\'s_degree_or_higher',
    'population_16_years_and_over_with_earnings', 'median_earnings_(dollars)', 'full-time,_year-round_workers_with_earnings',
    '$1_to_$9,999_or_loss', '$10,000_to_$14,999', '$15,000_to_$24,999', '$25,000_to_$34,999',
    '$35,000_to_$49,999', '$50,000_to_$64,999', '$65,000_to_$74,999', '$75,000_to_$99,999', '$100,000_or_more'
]

In [86]:
age_df = pd.read_csv('../../datasets/cleaned_datasets/demographic_dataset/age.csv')
education_df = pd.read_csv('../../datasets/cleaned_datasets/demographic_dataset/education.csv')
income_df = pd.read_csv('../../datasets/cleaned_datasets/demographic_dataset/income.csv')

In [87]:
merged_df = age_df.merge(education_df, on='Area Code', how='inner')
merged_df = merged_df.merge(income_df, on='Area Code', how='inner')

In [88]:
merged_df.columns = merged_df.columns.str.strip().str.lower().str.replace(' ', '_')
print(merged_df.columns)
merged_df.head()
# merged_df['area_code']

Index(['unnamed:_0_x', 'area_code', 'total_population', 'age', 'under_5_years',
       '5_to_9_years', '10_to_14_years', '15_to_19_years', '20_to_24_years',
       '25_to_29_years', '30_to_34_years', '35_to_39_years', '40_to_44_years',
       '45_to_49_years', '50_to_54_years', '55_to_59_years', '60_to_64_years',
       '65_to_69_years', '70_to_74_years', '75_to_79_years', '80_to_84_years',
       '85_years_and_over', 'unnamed:_0_y', 'less_than_high_school_graduate',
       'high_school_graduate', 'some_college_or_associate's_degree',
       'bachelor's_degree_or_higher', 'unnamed:_0',
       'population_16_years_and_over_with_earnings',
       'median_earnings_(dollars)',
       'full-time,_year-round_workers_with_earnings', '$1_to_$9,999_or_loss',
       '$10,000_to_$14,999', '$15,000_to_$24,999', '$25,000_to_$34,999',
       '$35,000_to_$49,999', '$50,000_to_$64,999', '$65,000_to_$74,999',
       '$75,000_to_$99,999', '$100,000_or_more'],
      dtype='object')

,unnamed:_0_x,area_code,total_population,age,under_5_years,5_to_9_years,10_to_14_years,15_to_19_years,20_to_24_years,25_to_29_years,...,"full-time,_year-round_workers_with_earnings","$1_to_$9,999_or_loss","$10,000_to_$14,999","$15,000_to_$24,999","$25,000_to_$34,999","$35,000_to_$49,999","$50,000_to_$64,999","$65,000_to_$74,999","$75,000_to_$99,999","$100,000_or_more"
0,2,19104,"54,454",NaN,"1,652","2,397","1,902","10,886","12,690","6,346",...,"12,543",396,444,777,"1,838","2,636","2,172",959,"1,523","1,798"
1,3,19106,"14,421",NaN,319,97,162,52,899,"2,520",...,"7,864",52,60,158,79,472,534,526,"2,026","3,957"
2,4,19107,"15,478",NaN,71,318,268,692,"2,337","3,518",...,"7,034",8,81,250,406,717,946,833,"1,512","2,281"
3,5,19108,162,NaN,18,0,0,0,0,39,...,124,0,0,0,0,0,0,12,63,49
4,6,19109,0,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
merged_df['area_code'] = merged_df['area_code'].astype(str)
merged_df[merged_df['area_code'] == '19104'].head()

,unnamed:_0_x,area_code,total_population,age,under_5_years,5_to_9_years,10_to_14_years,15_to_19_years,20_to_24_years,25_to_29_years,...,"full-time,_year-round_workers_with_earnings","$1_to_$9,999_or_loss","$10,000_to_$14,999","$15,000_to_$24,999","$25,000_to_$34,999","$35,000_to_$49,999","$50,000_to_$64,999","$65,000_to_$74,999","$75,000_to_$99,999","$100,000_or_more"
0,2,19104,"54,454",NaN,"1,652","2,397","1,902","10,886","12,690","6,346",...,"12,543",396,444,777,"1,838","2,636","2,172",959,"1,523","1,798"

In [90]:
geojson_path = "../../datasets/cleaned_datasets/philly_boundaries/Zipcodes_Poly.geojson"
geojson = gpd.read_file(geojson_path)

In [91]:
merged_df.rename(columns={'area_code': 'CODE'}, inplace=True)

In [92]:
merged_df[merged_df['CODE'] == '19104'].head()

,unnamed:_0_x,CODE,total_population,age,under_5_years,5_to_9_years,10_to_14_years,15_to_19_years,20_to_24_years,25_to_29_years,...,"full-time,_year-round_workers_with_earnings","$1_to_$9,999_or_loss","$10,000_to_$14,999","$15,000_to_$24,999","$25,000_to_$34,999","$35,000_to_$49,999","$50,000_to_$64,999","$65,000_to_$74,999","$75,000_to_$99,999","$100,000_or_more"
0,2,19104,"54,454",NaN,"1,652","2,397","1,902","10,886","12,690","6,346",...,"12,543",396,444,777,"1,838","2,636","2,172",959,"1,523","1,798"

In [93]:
print("Unique codes in merged_df:", merged_df['CODE'].unique()[:10])
print("Unique codes in geojson:", geojson['CODE'].unique()[:10])

merged_df['CODE'] = merged_df['CODE'].str.strip()
geojson['CODE'] = geojson['CODE'].str.strip()

print("Null values in merged_df['CODE']:", merged_df['CODE'].isnull().sum())
print("Null values in geojson['CODE']:", geojson['CODE'].isnull().sum())

Unique codes in merged_df: ['19104' '19106' '19107' '19108' '19109' '19111' '19112' '19113' '19114'
 '19115']
Unique codes in geojson: ['19120' '19121' '19122' '19123' '19124' '19125' '19126' '19127' '19128'
 '19102']
Null values in merged_df['CODE']: 0
Null values in geojson['CODE']: 0

In [94]:
merged_gdf = geojson.merge(merged_df, on='CODE', how='left')

In [95]:
merged_gdf[merged_gdf['CODE'] == '19104'].head()

,OBJECTID,CODE,COD,Shape__Area,Shape__Length,geometry,unnamed:_0_x,total_population,age,under_5_years,...,"full-time,_year-round_workers_with_earnings","$1_to_$9,999_or_loss","$10,000_to_$14,999","$15,000_to_$24,999","$25,000_to_$34,999","$35,000_to_$49,999","$50,000_to_$64,999","$65,000_to_$74,999","$75,000_to_$99,999","$100,000_or_more"
11,12,19104,4,1.390888e+07,16661.960198,"POLYGON ((-75.20436 39.97443, -75.20372 39.974...",2.0,"54,454",NaN,"1,652",...,"12,543",396.0,444.0,777,"1,838","2,636","2,172",959,"1,523","1,798"

In [96]:
if 'date' in merged_gdf.columns:
    merged_gdf['date'] = pd.to_datetime(merged_gdf['date'], errors='coerce')
    merged_gdf['date'] = merged_gdf['date'].dt.strftime('%Y-%m-%d')

In [97]:
m = folium.Map(location=[39.9526, -75.1652], zoom_start=12)
folium.TileLayer('cartodb positron').add_to(m)

In [98]:
folium.GeoJson(
    merged_gdf,
    name="ZIP Code Boundaries",
    style_function=lambda x: {
        'fillColor': 'blue',
        'color': 'black',
        'weight': 1,
        'fillOpacity': 0.2
    },
    tooltip=folium.GeoJsonTooltip(
        fields=['CODE', 'total_population', 'median_earnings_(dollars)'],
        aliases=["ZIP Code:", "Total Population:", "Median Earnings:"],
        localize=True
    ),
    popup=folium.GeoJsonPopup(fields=['CODE', 'total_population', 'median_earnings_(dollars)'])
).add_to(m)

In [99]:
folium.LayerControl().add_to(m)

In [100]:
m.save('philly_demographics_map_with_tooltips.html')